<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/User/User.Master" AutoEventWireup="true" CodeBehind="Anasayfa.aspx.cs" Inherits="SATIS_SITESI.Pages.User.Index" %>

<%@ Register Assembly="DevExpress.Web.v16.1, Version=16.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web" TagPrefix="dx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../../Style/Anasayfa.css" rel="stylesheet" />

  </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">   
    
    <div class="slider">
        <dx:ASPxImageSlider ID="ASPxImageSlider1" CssClass="ASPxImageSlider1" runat="server" ImageSourceFolder="~/Img/DevSlider/">
            <SettingsSlideShow AutoPlay="True" Interval="3000" />
            <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" ImageHeight="400px" ImageWidth="600px" />
            <Styles>
                <ImageArea BackColor="White">
                </ImageArea>
                <Item BackColor="White">
                </Item>
                <Disabled BackColor="White">
                </Disabled>
            </Styles>
        </dx:ASPxImageSlider>
    </div>
               
    <div class="uye">
        <asp:Repeater ID="Repeater1" runat="server" DataSourceID="UrunBilgisi">
            <ItemTemplate>
                <a href="Anasayfa.aspx">
                   <div class="urun-div">   
                        <div id="UrunResim">
                            <img src="<%#Eval("RESIM_YOL") %>" alt="<%#Eval("RESIM_YOL") %>" id="resimler"/>             
                        </div>   
                       <div class="urunBilgileri">
                           <asp:LinkButton ID="LinkButton1" CssClass="urunDetay" runat="server" PostBackUrl='<%# "DirektSatinAl.aspx?urunID="+Eval("URUN_ID") %>'>Ürün Detay</asp:LinkButton>
                            <span id="urunMarka"><%#Eval("MARKA_ADI") %></span>
                            <span id="urunModel"><%#Eval("MODEL_ADI") %></span>
                            <span id="urunIndirimliFiyat"><%#Eval("INDIRIMLI_FIYAT") %></span>  
                            <asp:Button CssClass="sepet" runat="server" Text="SEPETE EKLE" PostBackUrl='<%# "Anasayfa.aspx?urunID="+Eval("URUN_ID") %>' />
                            <asp:Button CssClass="satinAl" runat="server" Text="SATIN AL" PostBackUrl='<%# "DirektSatinAl.aspx?urunID="+Eval("URUN_ID") %>'/>
                       </div>                 
                   </div>
                </a>
            </ItemTemplate>
        </asp:Repeater>  
        <asp:SqlDataSource ID="UrunBilgisi" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT TOP 9 * FROM [URUNLER] ORDER BY NEWID()"></asp:SqlDataSource>
    </div>
</asp:Content>
