<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="devExp.aspx.cs" Inherits="SATIS_SITESI.devExp" %>

<%@ Register Assembly="DevExpress.Web.v16.1, Version=16.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web" TagPrefix="dx" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <dx:ASPxImageSlider runat="server" ImageSourceFolder="~/Img/">
            <SettingsSlideShow AutoPlay="True" />
            <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
            <Images ImageFolder="~/Img/">
            </Images>
        </dx:ASPxImageSlider>
    </div>
    </form>
</body>
</html>
