<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="KategoriEkle.aspx.cs" Inherits="SATIS_SITESI.Pages.Admin.KategoriEkle" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../../Style/Kategori.css" rel="stylesheet" />
    <link href="../../Style/Kategori.css" rel="stylesheet" />
    <style type="text/css">
        .katEkleButon {}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="kategori">
        <h3>Kategori Ekle</h3>
        <table>
            <tr>
                <td><asp:Label ID="Label1" runat="server" Text="KATEGORİ SEÇ"></asp:Label></td>
                <td><asp:DropDownList ID="katIDDrop" runat="server" DataSourceID="SqlDataSource1" DataTextField="KATEGORI_ADI" DataValueField="KATEGORI_ID" CssClass="katIDDrop"></asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [KATEGORILER]"></asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td><asp:Label ID="Label2" runat="server" Text="KATEGORİ ADI"></asp:Label></td>
                <td><asp:TextBox ID="kategoriText" runat="server" CssClass="kategoriText"></asp:TextBox></td>
            </tr>
            <tr>
                <td></td>
                <td><asp:ImageButton ID="ImageButton1" CssClass="accept" runat="server" ImageUrl="~/Img/accept.png"  OnClick="ImageButton1_Click" /></td>
            </tr>
        </table>
    </div>
    <div class="clear"></div>
    <div class="kategoriSil">
        <h3>KATEGORİLER</h3>
        <asp:GridView ID="GridView1"  runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="KATEGORI_ID" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" Width="739px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="KATEGORI_ID" HeaderText="KATEGORİ ID" InsertVisible="False" ReadOnly="True" SortExpression="KATEGORI_ID" />
                <asp:BoundField DataField="KATEGORI_ADI" HeaderText="KATEGORİ ADI" SortExpression="KATEGORI_ADI" />
                <asp:BoundField DataField="ALT_KATEGORI_ID" HeaderText="ALT KATEGORİ ID" SortExpression="ALT_KATEGORI_ID" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [KATEGORILER]"></asp:SqlDataSource>
    </div>
</asp:Content>
