<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="KullaniciEkle.aspx.cs" Inherits="SATIS_SITESI.Pages.Admin.KullaniciEkle" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../../Style/Kullanici.css" rel="stylesheet" />
    <style type="text/css">
        .kullaniciGrid {}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div >
        <div class="kullanici">
        <h3>KULLANICI EKLE </h3>
        <table>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label1" runat="server" Text="Adı"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="kadText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label2" runat="server" Text="Soyad"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="soyadText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style4"><asp:Label ID="Label3" runat="server" Text="Şifre"></asp:Label></td>
                <td class="auto-style5"><asp:TextBox ID="sifreText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label4" runat="server" Text="Şifre Tekrar"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="sifreTekrarText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label5" runat="server" Text="E-Posta"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="mailText" runat="server" Width="180px"></asp:TextBox>
                    <asp:RegularExpressionValidator ID="emailValidation" runat="server" ControlToValidate="mailText" ErrorMessage="Lütfen Geçerli Bir E-Posta Adresi Giriniz." Font-Italic="True" Font-Size="18px" ForeColor="#FF3300" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
                </td>
            </tr>
            <tr>
               <td class="auto-style3"><asp:Label ID="Label6" runat="server" Text="Cinsiyet"></asp:Label></td>
                <td class="auto-style2">
                    <asp:DropDownList ID="cinsiyetDrop" runat="server" CssClass="cinsiyetDrop">
                        <asp:ListItem Selected="True">BAY</asp:ListItem>
                        <asp:ListItem>BAYAN</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label7" runat="server" Text="Yaş"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="yasText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style3"><asp:Label ID="Label8" runat="server" Text="Telefon Numarası"></asp:Label></td>
                <td class="auto-style2"><asp:TextBox ID="telText" runat="server" Width="180px"></asp:TextBox></td>                
            </tr>
             <tr>
                <td class="auto-style3"><asp:Label ID="Label9" runat="server" Text="Yetki"></asp:Label></td>
                <td class="auto-style2"><asp:DropDownList ID="yetkiDrop" runat="server" CssClass="userDrop">
                    <asp:ListItem>User</asp:ListItem>
                    <asp:ListItem>Admin</asp:ListItem>
                    </asp:DropDownList></td>                
            </tr>
            <tr>
                <td class="auto-style3"></td>
                <td class="auto-style2"><asp:Button ID="Button1" runat="server" Text="Ekle" OnClick="Button1_Click" CssClass="kulEkleButon" /></td>
            </tr>
        </table>
    </div>
    </div>
    <div class="clear"></div>
   <%-- Kullanıcılar --%>
    <div class="kullanicilar">
        <h3>TÜM KULLANICILAR</h3>
        <asp:GridView ID="GridView1" CssClass="kullaniciGrid" runat="server" Width="200px" AutoGenerateColumns="False" DataKeyNames="KULLANICI_ID" DataSourceID="UsersDataSource" CellPadding="4" ForeColor="#333333" GridLines="None" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="KULLANICI_ID" HeaderText="KULLANICI ID" InsertVisible="False" ReadOnly="True" SortExpression="KULLANICI_ID" />
                <asp:BoundField DataField="KULLANICI_AD" HeaderText="AD" SortExpression="KULLANICI_AD" />
                <asp:BoundField DataField="KULLANICI_SOYAD" HeaderText="SOYAD" SortExpression="KULLANICI_SOYAD" />
                <asp:BoundField DataField="KULLANICI_SİFRE" HeaderText="SİFRE" SortExpression="KULLANICI_SİFRE" />
                <asp:BoundField DataField="KULLANICI_EPOSTA" HeaderText="EPOSTA" SortExpression="KULLANICI_EPOSTA" />
                <asp:BoundField DataField="YETKI" HeaderText="YETKİ" SortExpression="YETKI" />
                <asp:BoundField DataField="KULLANICI_CINSIYET" HeaderText="CİNSİYET" SortExpression="KULLANICI_CINSIYET" />
                <asp:BoundField DataField="KULLANICI_YAS" HeaderText="YAS" SortExpression="KULLANICI_YAS" />
                <asp:BoundField DataField="KULLANICI_TELEFON_NO" HeaderText="TELEFON" SortExpression="KULLANICI_TELEFON_NO" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="UsersDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [KULLANICI]"></asp:SqlDataSource>
    </div>
   <%--Kullanıcı Div Bitiş--%>
</asp:Content>
