<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="MarkaEkle.aspx.cs" Inherits="SATIS_SITESI.Pages.Admin.MarkaEkle" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 80px;
        }
        .auto-style2 {
            width: 108px;
        }
        .auto-style3 {
            width: 236px;
        }
        .markaText {}
        .markaEkle {}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="markaEkle">
        <h3>Marka Gir</h3>
        <table>
            <tr>
                <td class="auto-style2">
                    <asp:Label ID="Label1" runat="server" Text="Marka Adı "></asp:Label>
                </td>
                <td class="auto-style3">
                    <asp:TextBox ID="markaText" CssClass="markaText" runat="server" Width="206px"></asp:TextBox>
                </td>
                <td>
                    <asp:Button ID="Button1" CssClass="markaEkle" runat="server" Text="Ekle" OnClick="Button1_Click" Width="67px" />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label2" runat="server" Text="-" Visible="False"></asp:Label>
                </td>
            </tr>
        </table>
    </div>
    <div class="markalar">
        <h3>MARKALAR</h3>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="MARKA_ID" DataSourceID="MarkaSource" ForeColor="#333333" GridLines="None" Height="204px" Width="565px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="MARKA_ID" HeaderText="MARKA_ID" InsertVisible="False" ReadOnly="True" SortExpression="MARKA_ID" />
                <asp:BoundField DataField="MARKA_AD" HeaderText="MARKA_AD" SortExpression="MARKA_AD" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="MarkaSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [MARKA]"></asp:SqlDataSource>
    </div>
</asp:Content>
