<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="ModelEkle.aspx.cs" Inherits="SATIS_SITESI.Pages.Admin.ModelEkle" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="model">
        <table style="width: 486px">
            <tr>
                <td>
                    <asp:Label ID="Label1" runat="server" Text="Marka Seç"></asp:Label>
                </td>
                <td>
                    <asp:DropDownList ID="markaDrop" runat="server" AutoPostBack="True" DataSourceID="MarkaDataSource" DataTextField="MARKA_AD" DataValueField="MARKA_ID" style="margin-left: 4px" Width="186px"></asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label2" runat="server" Text="Model Gir"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="modelText" runat="server" style="margin-left: 6px" Width="180px"></asp:TextBox>
                </td>
                <td>
                    <asp:Button ID="Button1" runat="server" Text="Ekle" OnClick="Button1_Click" Width="60px" />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label3" runat="server" Text="-" Visible="False"></asp:Label>
                </td>
            </tr>
        </table>
        

        <asp:SqlDataSource ID="MarkaDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [MARKA]"></asp:SqlDataSource>
    </div>
    <div class="modelSil">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataSourceID="ModelDataSource" ForeColor="#333333" GridLines="None" Width="524px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="MARKA_ID" HeaderText="MARKA ID" SortExpression="MARKA_ID" />
                <asp:BoundField DataField="MODEL_AD" HeaderText="MODEL ADI" SortExpression="MODEL_AD" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="ModelDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [MODEL]"></asp:SqlDataSource>
    </div>
</asp:Content>
