<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="UrunEkle.aspx.cs" Inherits="SATIS_SITESI.Pages.Admin.UrunEkle" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../../Style/UrunEkle.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            width: 123px;
        }
        .auto-style2 {
            width: 163px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="urunEkle-div">
        <table>
            <tr>
                <td class="auto-style2"></td>
                 <td></td>
            </tr>
             <tr>
                 <td class="auto-style2">ÜRÜN ADI</td>
                 <td><asp:TextBox ID="urunAdText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
             <tr>
                <td class="auto-style2">MARKA</td>
                 <td><asp:DropDownList ID="markaDrop" runat="server" DataSourceID="markaDataSource" DataTextField="MARKA_AD" DataValueField="MARKA_ID" OnSelectedIndexChanged="markaDrop_SelectedIndexChanged" AutoPostBack="True" CssClass="markaDrop"></asp:DropDownList>
                     <asp:SqlDataSource ID="markaDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [MARKA]"></asp:SqlDataSource>
                 </td>
            </tr>
             <tr>
                <td class="auto-style2">MODEL</td>
                 <td><asp:DropDownList ID="modelDrop" runat="server" CssClass="modelDrop"></asp:DropDownList></td>
            </tr>
             <tr>
                <td class="auto-style2">ÜRÜN FİYAT</td>
                 <td><asp:TextBox ID="fiyatText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
             <tr>
                <td class="auto-style2">İNDİRİM ORANI</td>
                 <td><asp:TextBox ID="indirimText" runat="server" Width="180px"></asp:TextBox></td>
            </tr>
            <tr>
                <td class="auto-style2">RESİM SEÇ </td>
                <td><asp:FileUpload ID="resimUpload" runat="server" Width="180px" /></td>
            </tr>  
            <tr>
                <td class="auto-style2">KATEGORİ SEÇ </td>
                <td><asp:DropDownList ID="kategoriDrop" runat="server" DataSourceID="kategoriDataSource" DataTextField="KATEGORI_ADI" DataValueField="KATEGORI_ID" CssClass="kategoriDrop"></asp:DropDownList>
                    <asp:SqlDataSource ID="kategoriDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" SelectCommand="SELECT * FROM [KATEGORILER]"></asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td class="auto-style2"></td>
                <td><asp:Button ID="urunEkleButon" runat="server" Text="EKLE" OnClick="urunEkleButon_Click" CssClass="urunEkleButon" /></td>
            </tr>
        </table>
    </div>
    <div class="clear"></div>
    <div class="urunlerDiv">
        <h3>ÜRÜN BİLGİLERİ</h3>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="URUN_ID" DataSourceID="UrunlerDataSource" ForeColor="#333333" GridLines="None" Width="808px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="URUN_ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="URUN_ID" />
                <asp:BoundField DataField="URUN_ADI" HeaderText="ADI" SortExpression="URUN_ADI" />
                <asp:BoundField DataField="MARKA_ADI" HeaderText="MARKA" SortExpression="MARKA_ADI" />
                <asp:BoundField DataField="MODEL_ADI" HeaderText="MODEL" SortExpression="MODEL_ADI" />
                <asp:BoundField DataField="URUN_FIYAT" HeaderText="URUN" SortExpression="URUN_FIYAT" />
                <asp:BoundField DataField="INDIRIMLI_FIYAT" HeaderText="İNDİRİMLİ FİYAT" SortExpression="INDIRIMLI_FIYAT" />
                <asp:BoundField DataField="INDIRIM_ORANI" HeaderText="İNDİRİM %" SortExpression="INDIRIM_ORANI" />
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="UrunlerDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceDatabaseConnectionString %>" DeleteCommand="DELETE FROM [URUNLER] WHERE [URUN_ID] = @URUN_ID" InsertCommand="INSERT INTO [URUNLER] ([URUN_ADI], [MARKA_ADI], [MODEL_ADI], [URUN_FIYAT], [INDIRIMLI_FIYAT], [INDIRIM_ORANI], [RESIM_YOL], [KATEGORI_ID], [SATIS_ID], [STOK_ID]) VALUES (@URUN_ADI, @MARKA_ADI, @MODEL_ADI, @URUN_FIYAT, @INDIRIMLI_FIYAT, @INDIRIM_ORANI, @RESIM_YOL, @KATEGORI_ID, @SATIS_ID, @STOK_ID)" SelectCommand="SELECT * FROM [URUNLER]" UpdateCommand="UPDATE [URUNLER] SET [URUN_ADI] = @URUN_ADI, [MARKA_ADI] = @MARKA_ADI, [MODEL_ADI] = @MODEL_ADI, [URUN_FIYAT] = @URUN_FIYAT, [INDIRIMLI_FIYAT] = @INDIRIMLI_FIYAT, [INDIRIM_ORANI] = @INDIRIM_ORANI, [RESIM_YOL] = @RESIM_YOL, [KATEGORI_ID] = @KATEGORI_ID, [SATIS_ID] = @SATIS_ID, [STOK_ID] = @STOK_ID WHERE [URUN_ID] = @URUN_ID">
            <DeleteParameters>
                <asp:Parameter Name="URUN_ID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="URUN_ADI" Type="String" />
                <asp:Parameter Name="MARKA_ADI" Type="String" />
                <asp:Parameter Name="MODEL_ADI" Type="String" />
                <asp:Parameter Name="URUN_FIYAT" Type="Decimal" />
                <asp:Parameter Name="INDIRIMLI_FIYAT" Type="Decimal" />
                <asp:Parameter Name="INDIRIM_ORANI" Type="Int32" />
                <asp:Parameter Name="RESIM_YOL" Type="String" />
                <asp:Parameter Name="KATEGORI_ID" Type="Int32" />
                <asp:Parameter Name="SATIS_ID" Type="Int32" />
                <asp:Parameter Name="STOK_ID" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="URUN_ADI" Type="String" />
                <asp:Parameter Name="MARKA_ADI" Type="String" />
                <asp:Parameter Name="MODEL_ADI" Type="String" />
                <asp:Parameter Name="URUN_FIYAT" Type="Decimal" />
                <asp:Parameter Name="INDIRIMLI_FIYAT" Type="Decimal" />
                <asp:Parameter Name="INDIRIM_ORANI" Type="Int32" />
                <asp:Parameter Name="RESIM_YOL" Type="String" />
                <asp:Parameter Name="KATEGORI_ID" Type="Int32" />
                <asp:Parameter Name="SATIS_ID" Type="Int32" />
                <asp:Parameter Name="STOK_ID" Type="Int32" />
                <asp:Parameter Name="URUN_ID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
