CREATE TABLE KULLANICI
(
	KULLANICI_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	KULLANICI_AD VARCHAR(50),
	KULLANICI_SÝFRE VARCHAR(50),
	KULLANICI_EPOSTA VARCHAR(50) CONSTRAINT CK_EPOSTA CHECK(KULLANICI_EPOSTA IN('%@%','%.com%')),
	YETKI TINYINT CONSTRAINT CK_YETKI CHECK (YETKI LIKE '[0-1]'),
	KULLANICI_SOYAD VARCHAR(50),
	KULLANICI_CINSIYET VARCHAR(5) CONSTRAINT CK_CINSIYET CHECK(KULLANICI_CINSIYET IN ('BAY','BAYAN')),
	KULLANICI_YAS TINYINT CONSTRAINT CK_YAS CHECK(KULLANICI_YAS>0),
	KULLANICI_TELEFON_NO VARCHAR(12),
	KULLANICI_ADRES_ID INT	
)

CREATE TABLE ADRES
(
	KULLANICI_ID INT,
	KULLANICI_ADRES_ID INT IDENTITY(100,1) NOT NULL PRIMARY KEY,
	SOKAK VARCHAR(30) CONSTRAINT CK_SOKAK CHECK(LEN(SOKAK)>=0),
	CADDE VARCHAR(30) CONSTRAINT CK_CADDE CHECK(LEN(CADDE)>=0),
	MAHALLE VARCHAR(30) CONSTRAINT CK_MAHALLE CHECK(LEN(MAHALLE)>=0),
	KAPI_NO VARCHAR(3) CONSTRAINT CK_KAPI_NO CHECK(KAPI_NO>=0),
	DAIRE_NO VARCHAR(3) CONSTRAINT CK_DAIRE_NO CHECK(DAIRE_NO>=0),
	ILCE VARCHAR(30) CONSTRAINT CK_ILCE CHECK(LEN(ILCE)>=0),
	SEHIR VARCHAR(30) CONSTRAINT CK_SEHIR CHECK(LEN(SEHIR)>=0),
	POSTA_KODU VARCHAR(5) CONSTRAINT CK_POSTA_KODU CHECK(POSTA_KODU>=0)
)

CREATE TABLE KATEGORILER
(
	KATEGORI_ID INT IDENTITY(200,1) NOT NULL PRIMARY KEY,
	KATEGORI_ADI VARCHAR(30),
	ALT_KATEGORI_ID INT	
)

CREATE TABLE YORUMLAR
(
	YORUM_ID INT IDENTITY(500,1) NOT NULL PRIMARY KEY,
	METIN VARCHAR CHECK (LEN (METIN) >= 0),
	BASLIK VARCHAR(30) CHECK (LEN(BASLIK)>=0),
	URUN_ID INT,
	KULLANICI_ID INT
)

CREATE TABLE URUNLER
(
	URUN_ID INT IDENTITY(600,1) NOT NULL PRIMARY KEY,
	URUN_ADI VARCHAR(40) CHECK (LEN(URUN_ADI)>=0),
	MARKA_ADI VARCHAR(40) CHECK (LEN(MARKA_ADI)>=0),
	MODEL_ADI VARCHAR(40) CHECK (LEN(MODEL_ADI)>=0),
	URUN_FIYAT MONEY CHECK (URUN_FIYAT>=0),
	INDIRIMLI_FIYAT MONEY CHECK (INDIRIMLI_FIYAT>=0),
	INDIRIM_ORANI INT CHECK(INDIRIM_ORANI>=0),
	RESIM_YOL VARCHAR(50) CHECK (LEN (RESIM_YOL)>=0),
	KATEGORI_ID INT,
	SATIS_ID INT,
	STOK_ID INT	
)

CREATE TABLE MARKA
(
	MARKA_ID INT IDENTITY(1,5) NOT NULL PRIMARY KEY,
	MARKA_AD VARCHAR(40)
)
CREATE TABLE MODEL
(
	MARKA_ID INT,
	MODEL_AD VARCHAR(40)
)
ALTER TABLE MODEL ADD CONSTRAINT FK_MODEL FOREIGN KEY (MARKA_ID) REFERENCES MARKA(MARKA_ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE STOK
(
	STOK_ID INT,
	URUN_STOK_ADET INT CHECK(URUN_STOK_ADET>=0),
	FIRMA_AD VARCHAR(40)CHECK (LEN (FIRMA_AD)>=0),
	URUN_ID INT,
	SATIS_ID INT IDENTITY(700,1) NOT NULL PRIMARY KEY
)

CREATE TABLE SATIS
(
	URUN_ID INT,
	ALIS_ADET INT CHECK(ALIS_ADET>=0),
	TOPLAM_TUTAR MONEY CHECK(TOPLAM_TUTAR>=0),
	SATIS_ID INT,
	KULLANICI_ID INT
)

ALTER TABLE KULLANICI ADD CONSTRAINT FK_ADRES FOREIGN KEY (KULLANICI_ID) REFERENCES ADRES(KULLANICI_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE KULLANICI ADD CONSTRAINT FK_YORUM FOREIGN KEY (KULLANICI_ID) REFERENCES YORUMLAR (KULLANICI_ID);

ALTER TABLE KATEGORILER ADD CONSTRAINT FK_URUN_KATEGORI REFERENCES URUNLER (KATEGORI_ID);

ALTER TABLE URUNLER ADD CONSTRAINT FK_URUN_YORUM FOREIGN KEY (URUN_ID) REFERENCES YORUMLAR(URUN_ID);
ALTER TABLE STOK ADD CONSTRAINT FK_URUN_STOK FOREIGN KEY (URUN_ID) REFERENCES STOK(URUN_ID);

ALTER TABLE STOK ADD CONSTRAINT FK_SATIS_ID FOREIGN KEY SATIS_ID REFERENCES SATIS (SATIS_ID);

ALTER TABLE STOK ADD CONSTRAINT FK_SATIS_ID FOREIGN KEY SATIS_ID REFERENCES SATIS (SATIS_ID);
ALTER TABLE STOK ADD UNIQUE(URUN_ID);
INSERT INTO KULLANICI VALUES ('Murat','user','muratayvali@hotmail.com',0,'Ayvalý','BAY',25,'05306566666',11)
INSERT INTO ADRES VALUES (5,'maçka','mehmet akif ersoy','mehmet akif ersoy cad.','1','195','Üsküdar','Ýstanbul','36546');
INSERT INTO KATEGORILER VALUES ('BÝLGÝSAYAR',1)
INSERT INTO KATEGORILER VALUES ('TABLET',2)
INSERT INTO KATEGORILER VALUES ('TELEVÝZYON',3)
INSERT INTO KATEGORILER VALUES ('TELEFON',4)
INSERT INTO KATEGORILER VALUES ('MOBÝLYA',5)
INSERT INTO KATEGORILER VALUES ('MASAÜSTÜ',1)
INSERT INTO KATEGORILER VALUES ('LAPTOP',1)
INSERT INTO KATEGORILER VALUES ('SAMSUNG',206)
INSERT INTO KATEGORILER VALUES ('DELL',206)

INSERT INTO URUNLER VALUES ('PC','CASPER','C44','1800',Null,15,'C:\Users\Lenovo\Desktop\Staj\img.png',206,0,2)
INSERT INTO STOK VALUES (1,50,'IBM',602)
INSERT INTO SATIS VALUES (602,1,2000,700,5)

EXEC PROC_ADRES_EKLE 5,'SOKAK1','CADDE1','MAHALLE1','11','111','ILCE','SEHIR1','34681';
EXEC PROC_KATEGORI_EKLE 'LG',4;
EXEC PROC_KULLANICI_EKLE 'Yusuf','User','yusufsilgu@hotmail.com',0,'SÝLGU','BAY',15,'046006666',3;
